# Generated by Django 4.1.9 on 2023-05-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='number',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
