# Generated by Django 4.1.9 on 2023-05-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='number',
        ),
        migrations.AddField(
            model_name='board',
            name='member_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='data',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='foodlist',
            table='foodlist',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
