# Generated by Django 4.1.9 on 2023-05-26 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_is_active_user_is_admin_user_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='member_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='number',
            new_name='board',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodlist',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
